### ISSUE TITLE
tslint: subpackage has the wrong TSLint version

### ISSUE THREAD

**Issue by christophercr** [NationalBankBelgium/code-style#14]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/code-style/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior
The TSLint version we support in this package is not the one mentioned in the [tslint subpackage](https://github.com/NationalBankBelgium/code-style/tree/master/lib/tslint/4.3.x). Based on the rules we have in our TSLint configuration I would say that we support at least [TSLint v5.10](https://github.com/palantir/tslint/releases/tag/5.10.0) and not v4.3 as it is mentioned in the subpackage.

## Expected behavior
The TSLint configuration in our subpackage should correctly match with the actual version of TSLint that is meant for.  I would say that we support at least [TSLint v5.10](https://github.com/palantir/tslint/releases/tag/5.10.0) and not v4.3 as it is mentioned in the subpackage because we are using for example the [`prefer-while`](https://github.com/NationalBankBelgium/code-style/blob/8013a485a12f56f073a4fcf5416105f050ccab7d/lib/tslint/4.3.x/tslint.json#L135) rule.

## Minimal reproduction of the problem with instructions
In the [tsconfig.json file of our `@nationalbankbelgium/code-style/tslint/4.3.x`](https://github.com/NationalBankBelgium/code-style/blob/master/lib/tslint/4.3.x/tslint.json) subpackage, we use some rules that are available as from [version 5.10](https://github.com/palantir/tslint/releases/tag/5.10.0) and not 4.3. for example: [`prefer-while`](https://github.com/NationalBankBelgium/code-style/blob/8013a485a12f56f073a4fcf5416105f050ccab7d/lib/tslint/4.3.x/tslint.json#L135)

## What is the motivation / use case for changing the behavior?
Provide configurations that actually correspond to the version they are supposed to target.

## Environment

<pre><code>
Angular version: X.Y.Z
Code Style version: 1.0.1

</code></pre>

**Comment by SuperITMan** [comment]
@christophercr Good catch ! 
Let's see how to fix that without breaking everything 😊

**Comment by christophercr** [comment]
I think we should remove the rules that are not from version 4.3.x (this cannot be considered a breaking change because it is meant for version 4.3) and put those new rules in different subpackage for 5.10
