### ISSUE TITLE
eslint: add configurations for ESLint with TypeScript (replacement of TSLint)

### ISSUE THREAD

**Issue by SuperITMan** [NationalBankBelgium/code-style#31]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/NationalBankBelgium/code-style/blob/master/CONTRIBUTING.md#got-a-question-or-problem
</code></pre>

## Current behavior

TSLint 6.0.0 (last version) is deprecated and encourages users to migrate on ESLint.

## Expected behavior

Code-Style should provide configuration files for ESLint with TypeScript.

Some links to help in the migration:
  - https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md
  - https://github.com/typescript-eslint/typescript-eslint
  - https://medium.com/palantir/tslint-in-2019-1a144c2317a9
  - https://github.com/typescript-eslint/tslint-to-eslint-config

## What is the motivation / use case for changing the behavior?

Provide a package containing configurations for the latest versions of the different tools used at the National Bank of Belgium.

## Environment

<pre><code>
Code Style version: 1.0.1

</code></pre>

**Comment by christophercr** [comment]
And also the replacement of Codelyzer for ESLint (although this is still in Alpha version): https://github.com/angular-eslint/angular-eslint

**Comment by mhenkens** [comment]
Could be close because configuration for eslint is [@nationalbankbelgium/eslint-config](https://github.com/NationalBankBelgium/eslint-config)

**Comment by SuperITMan** [comment]
TSLint has been replaced by ESLint and the configuration is now avaialble in https://github.com/NationalBankBelgium/eslint-config
